### ISSUE TITLE
Can't get help of second sub parser

### ISSUE THREAD

**Issue by aLagoG** [krassowski/declarative-parser#3]
First off great project, I really like it but...
Playing around with your **Nested and Parallel** example I noticed that there is no way to get the help of the second sub parser:
- If you run it like this `./example.py input image.png output -h` assuming all else goes well you get the help of input, not output
- If you run it without input i.e. `./example.py output -h` it fails with the following exception: `TypeError: %o format: an integer is required, not dict`

Maybe I'm missing something but any help would be appreciated

**Comment by krassowski** [comment]
Thank you for your report. This is an unexpected behavior, indeed.
If you replace the percent sign in the help text with word percent, the second option will start working:

```python
scale = Argument(type=int, default=100, help='Rescale image to percent of original size')
```
Another option is to escape the percent sign by repeating it: 
```python
scale = Argument(type=int, default=100, help='Rescale image to %% of original size')
```

I consider this a bug and will work on a fix or workaround. Thanks again!

**Comment by krassowski** [comment]
I improved the example and documentation. The escaping of '%' sign is required in all argparse help strings -  the aim is to facilitate use of special variables.
